### ISSUE TITLE
Replace openssl subprocess calls with python cryptography library

### ISSUE THREAD

**Issue by ruffsl** [ros2/sros2#109]
Currently, the sros2 api makes subprocess calls to the systems OpenSSL CLI for generating public/private x509 key pairs and signing for SMIME. This is a bit hacky, as it relies upon the OpenSSL CLI to be consistent across runtime targets, making it quite fragile should the CLI or implicit defaults change. Instead, we should seek to use a proper cryptography library API so we may have finer control over key material provisioning and error handling for the user.

For example, users wishing to use Connext for DDS Security must swap the environment to point to a version of OpenSSL shipped by RTI. As RTI’s OpenSSL installer does not fully configure the CLI, as it does instead for the shared library, nor does the install respect the system config defaults for OpenSSL; this results in warnings produced by the RTI OpenSSL CLI binary that are susiquentl silenced by sros2 use of subprocess, obscuring potential errors or deviating crypto settings.

---

## Background

> `cryptography` is a package which provides cryptographic recipes and primitives to Python developers. Our goal is for it to be your "cryptographic standard library". `cryptography` includes both high level recipes and low level interfaces to common cryptographic algorithms such as symmetric ciphers, message digests, and key derivation functions.  
https://cryptography.io

By far, my favorite python library for this is `cryptography`, which has a pythonic API, excellent documentation, and readily available for most targets. This what I also used back for SROS1 when developing its keyserver:  
https://github.com/ros/ros_comm/blob/f95b4a5de2acb4fb53f0e9a4cff47dcef928eac5/tools/rosgraph/src/rosgraph/key_helper.py

## Progress

While sros2 CLI was still in its early stages, I previously prototyped a more advanced keystore workspace tool called [Keymint](https://github.com/keymint/keymint_tools), again using the python `cryptography` library:

https://github.com/keymint/keymint_keymake/tree/adc38e07ce5f16d6ba4b36294d7d2e8a361153f0/keymint_keymake/pki

This allowed me to abstract a bit more allowing users to finally configure the asymmetric key algorithm/size/format, CA hierarchy, period of validity and expiration, file protection, etc. I’d like to port over most of these features directly into sros2, but would like to just start by swapping out the subprocess calls and establishing `cryptography` as a primary depency.

The only road bump is foresee is that of supporting SMIME signatures when notarizing DDS Security governance and permission documents. As of writing, the `cryptography` library doesn’t yet seem to have a simple API for producing smime signature. This has been an open ticket for a while:

https://github.com/pyca/cryptography/issues/1621

For Keyment, I worked out out this by using `M2Crypto` for this one purpose instead, allow me to replicate the same valid SMIME signatures in pure-ish python. However `M2Crypto` isn’t as simple to install (this may have improved since I last checked a year ago), and its API is more like OpenSSL (think: giant hairball):

https://github.com/keymint/keymint_keymake/blob/adc38e07ce5f16d6ba4b36294d7d2e8a361153f0/keymint_keymake/smime/sign.py

Still, I think we can avoid `M2Crypto` as a dependency if we temporarily drop down a little into the backend API and add some wrappers around the lowevel interfaces for SMIME signing:

https://stackoverflow.com/questions/52780716/signing-s-mime-content-from-python

**Comment by mikaelarguedas** [comment]
Great ! That's been an improvement we wanted to do for a long time, thanks for summarizing it here!

Too bad cryptography and M2Crypto situation didnt move regarding to SMIME since we looked a couple years ago.

> Still, I think we can avoid M2Crypto as a dependency if we temporarily drop down a little into the backend API and add some wrappers around the lowevel interfaces for SMIME signing:

That would be a great alternative for the time being, until `cryptography` supports it.

Is the version of cryptography in the ubuntu repository (2.1.4) recent enough for this? or would we need a more recent one ?

**Comment by ruffsl** [comment]
> Is the version of cryptography in the ubuntu repository (2.1.4) recent enough for this? or would we need a more recent one ?

I think so, at least the user facing x509 API has been quite stable for a number of years. But, I'll have to tryout the SMIME workaround from above on something ubuntu 18.04 debs.

**Comment by mjcarroll** [comment]
Another question would be Windows compatibility.  Is this dependency easily installed on Windows via pip?  Does that also include debug variants?  Looking to avoid the LXML headache again if at all possible.

**Comment by mjcarroll** [comment]
Possible, but may be slightly painful: https://cryptography.io/en/latest/installation/#building-cryptography-on-windows

Also, I don't see anything about ARM explicitly, but it may be implicitly supported.

**Comment by ruffsl** [comment]
> Another question would be Windows compatibility.
> Possible, but may be slightly painful

Do you mean the wheel package on Windows that is a statically linked build, or compiling it ourselves? I'm not sure how ROS2 dependencies are handled/resolved on MS Windows; pip3, chocolatey, tylenol? :face_with_head_bandage: 

> Also, I don't see anything about ARM explicitly, but it may be implicitly supported.

It looks like `python3-cryptography` has been upstreamed into Debian, and is available as a debian for Ubuntu +18.10 for all normally supported arm verents. 

https://packages.debian.org/jessie/python3-cryptography  
https://packages.ubuntu.com/cosmic/python3-cryptography

**Comment by mjcarroll** [comment]
> Do you mean the wheel package on Windows that is a statically linked build, or compiling it ourselves?

The wheel should be fine for release builds.  The largest sticking point (as discovered with `lxml`) is that when we do Windows Debug builds, we also use a debug python interpreter, which means that wheels additionally have to be available with debug symbols.  For pure python packages, this isn't an issue, but if the package has other compilation or binary dependencies, those need to be built as debug.

Now that I have the process down, it shouldn't be as much of as an issue if the package is well-formed.  `lxml` had some additional issues with dependencies not being available for our compiler/platform configuration, which made the rabbit hole a bit deeper.
