### ISSUE TITLE
test_policy_to_permissions failing

### ISSUE THREAD

**Issue by pbaughman** [ros2/sros2#157]
## Bug report
I'm having some trouble with the test_policy_to_permissions - but just today.  It's been fine for months:

```
test/test_policy_to_permissions.py:33: in test_policy_to_permissions
    policy_xsd = etree.XMLSchema(etree.parse(policy_xsd_path))
src/lxml/xmlschema.pxi:86: in lxml.etree.XMLSchema.__init__
    ???
E   lxml.etree.XMLSchemaParseError: attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}base' does not resolve to a(n) attribute declaration., line 34
- generated xml file: /path_to_workspace/build/sros2/pytest.xml -
```

I don't know as much about XML as I should, but I think the issue is in sros2/policy/schemas/policy.xsd

```
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
               schemaLocation="http://www.w3.org/2001/03/xml.xsd" />
```

I can't navigate to https://www.w3.org/2001/03/xml.xsd right now, and the test is failing.  I can see that this should be a page by looking at the google 'cached pages' link.  I'm pretty sure it's trying to fetch this schema from the internet and failing because the page is offline right now.

Would it be appropriate to copy this schema somewhere locally so our unit tests don't stop working if/when we can't access www.w3.org?

**Required Info:**

- Operating System:
  - 
NAME="Ubuntu"                        
VERSION="18.04.3 LTS (Bionic Beaver)"

- Installation type:
  -  from source
 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

This happens when we do colcon test.  You can also do it pretty easily in an ipython window:

```
from lxml import etree
etree.XMLSchema(etree.parse('/path_to_sros2/sros2/sros2/policy/schemas/policy.xsd'))
```

**Comment by kyrofa** [comment]
Thanks for the report, @pbaughman. We just saw this in the [nightly Windows tests](https://ci.ros2.org/job/test_ci_windows/62/testReport/junit/sros2.test/test_policy_to_permissions/test_policy_to_permissions/) as well.

**Comment by ruffsl** [comment]
Related: https://stackoverflow.com/a/15376988

**Comment by pbaughman** [comment]
Should I make a PR where this schema is included locally somewhere, or does someone who knows more about `lxml` know a better solution?

**Comment by ruffsl** [comment]
I feel like lxml should be doing this kind of thing for us. Perhaps we should ticket on the lxml issue tracker as well?

**Comment by pbaughman** [comment]
I poked around in the XML catalog on my system, and it doesn't look like I have anything that would help resolve `https://www.w3.org/2001/03/xml.xsd` or any of the attributes it defines locally

**Comment by pbaughman** [comment]
I have a proposed fix for the test here: https://github.com/ros2/sros2/pull/158
