### ISSUE TITLE
Dashing not compatable with RTI Connext DDS 6.0.0, which is the only one easily available

### ISSUE THREAD

**Issue by knickels** [ros2/sros2#163]
The instructions should probably warn the user that 6.0.0 isn't compatible with dashing.  I signed up for a license, installed, setup, got the demos, compiled them, then eventually found https://index.ros.org/doc/ros2/Installation/Install-Connext-University-Eval/ which warns us of the fact that dashing supports up to 5.3.x.  Sigh.

**Comment by dirk-thomas** [comment]
The Dashing release page mentions the supported platforms: https://index.ros.org/doc/ros2/Releases/Release-Dashing-Diademata/#supported-platforms

As described there you will find the details in [REP 2000](https://www.ros.org/reps/rep-2000.html#dashing-diademata-may-2019-may-2021) which explicitly names Connext 5.3.1.

**Comment by emersonknapp** [comment]
@dirk-thomas I don't think it's entirely fair to say that the messaging there is entirely clear. Yes, a user can find REP2000, but that doesn't mean it's obvious.

Is there a plan to support Connext 6.0 and if so can we link to that ticket here?
If not, is there a plan to deprecate Connext as a supported platform, since they do not provide past binary versions? (and if so, is there a ticket for that?) If a user can't get a dependency, it doesn't make a lot of sense to call that a "supported platform".

**Comment by dirk-thomas** [comment]
> I don't think it's entirely fair to say that the messaging there is entirely clear. Yes, a user can find REP2000, but that doesn't mean it's obvious.

Please feel free to propose an update wording through a pull request.

> Is there a plan to support Connext 6.0 and if so can we link to that ticket here?

ros2/rmw_connext#351

> is there a plan to deprecate Connext as a supported platform

No.

> they do not provide past binary versions?

These are the instructions which have been contributed by RTI in ros2/ros2_documentation#285: https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Development-Setup/#rti-connext-version-5-3-1-amd64-only

While I have to agree with you that it is cumbersome that you can't download the version from https://www.rti.com/free-trial/dds-files there is nothing we can do about. Please feel free to reach out to RTI and state your concern.

> If a user can't get a dependency, it doesn't make a lot of sense to call that a "supported platform".

A user can clearly get Connext. The path to download a free-of-charge version might be cumbersom but there is obviously user which pay for their Connext licenses. So Connext is a supported platform as stated in the REP.

**Comment by emersonknapp** [comment]
Thanks for the links! I think that resolves this ticket much more nicely.
