### ISSUE TITLE
[ERROR] [rcl]: Failed to fini publisher for node: 1

### ISSUE THREAD

**Issue by claireyywang** [ros2/sros2#166]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 18.04 
- Installation type: 
  - from source
- Version or commit hash:
  - Eloquent 
- DDS implementation: 
  - Fast-RTPS 
- Client library (if applicable): 
  - rcl, rmw_fastrtps_shared_cpp 

#### Steps to reproduce issue

```
cd ~/sros2_demo
ros2 security create_keystore demo_keys
ros2 security create_key demo_keys /talker
ros2 security create_key demo_keys /listener
export ROS_SECURITY_ROOT_DIRECTORY=~/sros2_demo/demo_keys
export ROS_SECURITY_ENABLE=true
export ROS_SECURITY_STRATEGY=Enforce
ros2 run demo_nodes_cpp talker
```

#### Expected behavior
talker node running and sending msg out.
#### Actual behavior
```
[INFO] [rcl]: Found security directory: /home/claire/sros2_demo/demo_keys/talker

>>> [rcutils|error_handling.c:107] rcutils_set_error_state()
This error state is being overwritten:

  'This Fast-RTPS version doesn't have the security libraries
Please compile Fast-RTPS using the -DSECURITY=ON CMake option, at /home/claire/ros2_ws/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/rmw_node.cpp:330, at /home/claire/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:336'

with this new error message:

  'rcl node's rmw handle is invalid, at /home/claire/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:485'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [rcl]: Failed to fini publisher for node: 1
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to initialize rcl node: rcl node's rmw handle is invalid, at /home/claire/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:485

```
might also just be due to my failure in building rmw_fastrtps_shared_cpp, verifying...

**Comment by mikaelarguedas** [comment]
Thanks for reporting.

From the error message 

```
'This Fast-RTPS version doesn't have the security libraries
Please compile Fast-RTPS using the -DSECURITY=ON CMake option, at /home/claire/ros2_ws/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/rmw_node.cpp:330, at /home/claire/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:336'
```
It looks like you omitted that flag when you compiled your ROS2 workspace

Can you try to compile your workspace following the instructions from this tutorial? https://github.com/ros2/sros2/blob/master/SROS2_Linux.md#install-from-source.

**Comment by claireyywang** [comment]
It's working now. Thanks for the help! 

Though for RTI Connext, this command `source ~/rti/rti_connext_dds-5.3.1/resource/scripts/rtisetenv_x64Linux3gcc5.4.0.bash` didn't work for me, cuz Im using the debian package of Connext from ros2 repos as instructed [here](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/#rti-connext-version-5-3-1-amd64-only).

It may be worth adding `cd /opt/rti.com/rti_connext_dds-5.3.1/resource/scripts && source ./rtisetenv_x64Linux3gcc5.4.0.bash; cd -` to source the setup file for users who installed Connext from ROS2 apt repos.
