### ISSUE TITLE
[Dashing/Eloquent] List keys doesn't list nested keys

### ISSUE THREAD

**Issue by ivanpauno** [ros2/sros2#183]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04 (should happen in any)
- Installation type:
  - from source (should happen in any)
- Version or commit hash:
  - master
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

```
ros2 security generate_artifacts -k tmp -n /node1 /ns/node1 /ns/node2
ros2 security list_keys tmp
```
#### Expected behavior
Output:
```
/node1
/ns/node1
/ns/node2
```

#### Actual behavior
Output:
```
node1
ns
```

#### Additional information

This should be fixed for Dashing/Eloquent, and also for Foxy after https://github.com/ros2/sros2/pull/177 is merged.
Add a regression test too.

**Comment by hidmic** [comment]
@ros2/security_working_group are you planning to take a stab at this one in the near term e.g. before Foxy feature freeze?

**Comment by kyrofa** [comment]
Do the still-in-flux design updates impact this at all?

**Comment by ivanpauno** [comment]
> Do the still-in-flux design updates impact this at all?

The fix for `Dashing` and `Eloquent` aren't blocked by those changes.
About `Foxy`, maybe `contexts` folder is renamed to `enclaves`, but it isn't a big deal to update the folder name in a follow up.

**Comment by ivanpauno** [comment]
Reopening to track the fix for Dashing/Eloquent

**Comment by mikaelarguedas** [comment]
Backported and released
Dashing: https://github.com/ros2/sros2/pull/223 https://github.com/ros/rosdistro/pull/25499
Eloquent: https://github.com/ros2/sros2/pull/222 https://github.com/ros/rosdistro/pull/25492
