### ISSUE TITLE
Update security environment variables

### ISSUE THREAD

**Issue by ruffsl** [ros2/sros2#199]
## Feature request

With the update to enclaves, the security environment variables could also use some updates. To  future proof variables. allowing for more exotic keystore URIs, like remote URL (https://...$TOKEN) or TPM devices (tpm://...$KEY), it would be advantageous to take the opportunity to name them more appropriately while generalizing across keystore types. E.g. integrating with more advanced secret management: https://www.vaultproject.io

The following renaming is proposed:

* `ROS_SECURITY_ROOT_DIRECTORY` -> `ROS_SECURITY_KEYSTORE`
* `ROS_SECURITY_DIRECTORY_OVERRIDE` -> `ROS_SECURITY_ENCLAVE_OVERRIDE`

Additionally, to abstract above directories or file paths, I'd also like to sagest that `ROS_SECURITY_ENCLAVE_OVERRIDE` takes instead a fully qualified enclave name, instead of a absolute file path to an enclave directory. The use of the env `ROS_SECURITY_KEYSTORE` would then consistently control keystore URI (currently a file system path) and always be used to resolve the context location, regardless if context name is overridden or not.

This could help guide users that secure ros2 nodes will only communicate with nodes that share a common source of trust, or common CA. If the user has multiple keystores on disk, they may be likely to use `ROS_SECURITY_DIRECTORY_OVERRIDE` to point to an entirely different keystore than the rest of the launched nodes, rendering potentially cryptic looking security handshake errors from Secure DDS vendor plugins given the empty overlap of trusted certificate authorities.

For users who know what they are doing, they can still set the `ROS_SECURITY_KEYSTORE` uniquely for each process if they do intend on separate processes having separate keystores.

---

https://github.com/ruffsl/ros2/blob/security_env/ros2.repos

**Comment by ivanpauno** [comment]
Testing `rcl`, `test_security`, `sros2`.
Only `Fast-RTPS`.

- Focal [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10212)](https://ci.ros2.org/job/ci_linux/10212/)
- AArch64 Bionic [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5760)](https://ci.ros2.org/job/ci_linux-aarch64/5760/)
- macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8301)](https://ci.ros2.org/job/ci_osx/8301/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10101)](https://ci.ros2.org/job/ci_windows/10101/)

**Comment by mikaelarguedas** [comment]
DIdnt get a chance to review everything but as there are several approvals :+1:

> Testing rcl, test_security, sros2.
> Only Fast-RTPS.

Is it possible to run CI with Connext instead? security tests are currently disabled for Fast-RTPS (https://github.com/ros2/system_tests/pull/413)

**Comment by ivanpauno** [comment]
> Is it possible to run CI with Connext instead? security tests are currently disabled for Fast-RTPS (ros2/system_tests#413)

Good call, doing that in `linux`, where the tests are disabled:

- Focal [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10214)](https://ci.ros2.org/job/ci_linux/10214/)

**Comment by mikaelarguedas** [comment]
Can you please un them on all platforms? the previous CI stopped at sros2 so didn't run any tests from the `test_security` package. Also the `test_security` Fast-RTPS tests are disabled on all platforms, not just linux

**Comment by ivanpauno** [comment]
- macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8310)](https://ci.ros2.org/job/ci_osx/8310/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10110)](https://ci.ros2.org/job/ci_windows/10110/)

**Comment by ivanpauno** [comment]
@ruffsl there seem to be failures on macOS and Windows.

**Comment by ruffsl** [comment]
@ivanpauno I just pushed a fix for `rcl.TestGetSecureRoot.test_get_security_options` for windows https://github.com/ros2/rcl/pull/617/commits/3e067b45369963b17aec7c265b07271d73bd00b9 . Not sure how these PRs would effected the timeout or shutdown tests.
I don't have a mac or windows licence to debug those. Where those failures introduced here?

**Comment by mikaelarguedas** [comment]
Another round of CI with fixes from https://github.com/ros2/rcl/pull/617/commits/68a356ef59d7e29e9505a917b3931d75d24b2bd5
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10248)](http://ci.ros2.org/job/ci_linux/10248/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8330)](http://ci.ros2.org/job/ci_osx/8330/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10130)](http://ci.ros2.org/job/ci_windows/10130/)

**Comment by ivanpauno** [comment]
> I don't have a mac or windows licence to debug those. Where those failures introduced here?

The macOS ones are also happening in nightlies and https://github.com/ros2/system_tests/pull/409 is needed to fix them.

**Comment by ivanpauno** [comment]
@ruffsl can you check linter failures?

**Comment by mikaelarguedas** [comment]
I submitted a suggestion at https://github.com/ros2/rcl/pull/617#pullrequestreview-394632881 that should hopefully address them

**Comment by ruffsl** [comment]
> I submitted a suggestion

Thanks, merged.

**Comment by ivanpauno** [comment]
Final run, checking that linter failures are gone:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10251)](http://ci.ros2.org/job/ci_linux/10251/)

**Comment by ivanpauno** [comment]
I think everything was merged, thanks @ruffsl !

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-04-16/13709/1
