### ISSUE TITLE
Release for Foxy

### ISSUE THREAD

**Issue by clalancette** [ros2/sros2#202]
Hello @ros2/security_working_group !  This is your friendly ROS 2 Foxy release team.  We are currently going through the process of blooming all of the packages in ros_core, and the last one to come up is sros2.  We believe all of the dependencies for sros2 are now available, so would you mind doing a release into Foxy?  Let us know if you need assistance or don't have time to do it.  Thanks.

**Comment by mikaelarguedas** [comment]
Hi! Similar to the discussion that happened a couple days ago in the matrix chat, the release is currently blocked by the lack of any passing security test on Foxy.
More details are available on this testing matrix: https://github.com/ros2/sros2/issues/180#issuecomment-611094883

We would love to get some assistance from OR to move those CI issues forward as this is mostly out of our reach. /cc @jacobperron

**Comment by clalancette** [comment]
> Hi! Similar to the discussion that happened a couple days ago in the matrix chat, the release is currently blocked by the lack of any passing security test on Foxy.
> More details are available on this testing matrix: [#180 (comment)](https://github.com/ros2/sros2/issues/180#issuecomment-611094883)

Ah, sorry, I wasn't aware of the matrix chat when I opened this.

> 
> We would love to get some assistance from OR to move those CI issues forward as this is mostly out of our reach. /cc @jacobperron

All right, I'll get together with @ivanpauno and @jacobperron and see what we can do to help this forward.

**Comment by mikaelarguedas** [comment]
sounds great!
Feel free to ping me if you need more details of what has been tried and what is currently unclear to us or not working

**Comment by kyrofa** [comment]
Sounds like we're also waiting on ros2cli for this.

**Comment by jacobperron** [comment]
> Sounds like we're also waiting on ros2cli for this.

How so? ros2cli is released into Foxy.

**Comment by mikaelarguedas** [comment]
> How so? ros2cli is released into Foxy.

This was a fluke of the blocked release page http://repo.ros2.org/status_page/blocked_releases_foxy.html?q=id%3D%22variants%22&s=6&r=1 ros2cli is still listed as a blocking repo but it's actually released

**Comment by mikaelarguedas** [comment]
actually we do rely on unreleased ros2cli feature https://github.com/ros2/ros2cli/pull/501

It shouldn't prevent the deb from building though but this means that the policy generation won't work until the next ros2cli version. @jacobperron should I open a ticket on ros2cli or will it be rereleased shortly anyway ?

**Comment by jacobperron** [comment]
I can make a patch release shortly so that it's there for testing.

**Comment by mikaelarguedas** [comment]
https://github.com/ros/rosdistro/pull/24745 :rocket:

**Comment by jacobperron** [comment]
ros2cli patch release: https://github.com/ros/rosdistro/pull/24746

**Comment by jacobperron** [comment]
I'm going to close this since we have a release for Foxy. But, I'd still like to make a concerted effort to make sure tests are enabled (and passing) for security on all platforms before the final Foxy release.
We have https://github.com/ros2/sros2/issues/180 for tracking.

@mikaelarguedas Thanks!
