### ISSUE TITLE
Regression on nightly builds sros2.src.ros2.sros2.sros2.test.sros2.commands.security.verbs.test_generate_policy.test_generate_policy_services

### ISSUE THREAD

**Issue by tfoote** [ros2/sros2#213]
## Bug report

`sros2.src.ros2.sros2.sros2.test.sros2.commands.security.verbs.test_generate_policy.test_generate_policy_services` is failing on multiple platforms on the nightly builds

**Required Info:**

- Operating System:
  - Linux aarch64r repeated:  https://ci.ros2.org/job/nightly_linux-aarch64_repeated/1192/testReport/
  - Linux repeated: https://ci.ros2.org/job/nightly_linux_repeated/1871/testReport/
   - Linux release: https://ci.ros2.org/job/nightly_linux_release/1542/testReport/
   - Fci too: http://build.ros2.org/job/Fci__nightly-fastrtps_ubuntu_focal_amd64/120/testReport/
   - OSX debug: https://ci.ros2.org/job/nightly_osx_debug/1624/testReport/
   - OSX repeated: https://ci.ros2.org/job/nightly_osx_repeated/1953/testReport/
- Installation type:
  - CI builds
- Version or commit hash:
  - May 14th nightly
- DDS implementation:
  - Default
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Run the CI: 

sros2.src.ros2.sros2.sros2.test.sros2.commands.security.verbs.test_generate_policy.test_generate_policy_services

#### Expected behavior

Tests pass

#### Actual behavior

Tests fail

**Comment by ruffsl** [comment]
The stacktrace from the failed test log doesn't seem informative:

``` python
test/sros2/commands/security/verbs/test_generate_policy.py:44: in test_generate_policy_topics
    assert cli.main(
E   AssertionError: assert 1 == 0
E    +  where 1 = <function main at 0xffffb1e529d0>(argv=['security', 'generate_policy', '/tmp/tmpi_bj77wj/test-policy.xml'])
E    +    where <function main at 0xffffb1e529d0> = cli.main
```

Is the python stacktrace being captured correctly?

**Comment by tfoote** [comment]
Well it's asserting here: https://github.com/ros2/sros2/blob/57e08d84a9c303d77bee681b1ac16dfc39ac6189/sros2/test/sros2/commands/security/verbs/test_generate_policy.py#L44 that the return code is zero so there's not much stack trace. The function has returned 1 already.

**Comment by kyrofa** [comment]
We've hit a difference in environment between the nightly tests and the normal ones in the past, could this be related to that?

**Comment by tfoote** [comment]
@kyrofa That would be surprising if something like that changed overnight, it's been working up until today. 

@hidmic Pointed out to me that this could be related: https://github.com/ros2/sros2/pull/212

**Comment by sloretz** [comment]
If I understand correctly, @hidmic's PR https://github.com/ros2/sros2/pull/214 might fix this

**Comment by mikaelarguedas** [comment]
This should be addressed by https://github.com/ros2/sros2/pull/214 so I'm going to close this. Feel free to comment here if the issue persists and we can reopen
