### ISSUE TITLE
How to see node and topic lists on a machine with security keys

### ISSUE THREAD

**Issue by JaehyunShim** [ros2/sros2#244]
#### Implementation considerations

The following commands do not show any information about running nodes and topics even on the machine with keys. Am I missing something to run? 
$ ros2 node list
$ ros2 topic list

**Comment by mikaelarguedas** [comment]
Thanks @JaehyunShim for reporting, however the recommended platform for ROS Q&A is [ROS Answers](http://answer.ros.org), please consider asking your questions there instead for the whole community to easily benefit from the answer
