### ISSUE TITLE
Release into Rolling

### ISSUE THREAD

**Issue by clalancette** [ros2/sros2#259]
Could we please get a new release into Rolling so that the binary Debian/RPM packages match what we are testing from source?  Alternatively, if the maintainers want, I can do the release.

Thank you!

**Comment by mikaelarguedas** [comment]
Is there value in waiting for fixes like https://github.com/ros2/sros2/pull/260 to land before making a new release ?

Or are test related changes irrelevant for your testing ?

**Comment by clalancette** [comment]
> Is there value in waiting for fixes like #260 to land before making a new release ?
> 
> Or are test related changes irrelevant for your testing ?

They are irrelevant.  Mostly we want to make sure that the code in the Debian packages matches what comes from the packaging jobs/from source.  Changes to improve tests don't matter for that.

**Comment by mikaelarguedas** [comment]
Sounds good, here is a rolling release: https://github.com/ros/rosdistro/pull/29111

Bloom is complaining because my version of bloom is to old but my system is up to date:
```This version of bloom is '0.10.3', but the newest available version is '0.10.6'. Please update.```

It looks like the ROS1 apt repo provides 0.10.3 while the ROS2 apt repo provides 0.10.6. Is it possible to sync the repos so that they provide the same version of the infrastructure packages ?

**Comment by clalancette** [comment]
> Sounds good, here is a rolling release: [ros/rosdistro#29111](https://github.com/ros/rosdistro/pull/29111)

Great, thank you!

> It looks like the ROS1 apt repo provides 0.10.3 while the ROS2 apt repo provides 0.10.6. Is it possible to sync the repos so that they provide the same version of the infrastructure packages ?

@nuclearsandwich Can you take a look?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich Can you take a look?

The upload_* jobs on build.ros.org weren't regenerated during the migration and so didn't have the  dependency on the import_upstream job so that new package uploads trigger an rsync between the build farm repositories and packages.ros.org just like the sync jobs do.

```
Connecting to Jenkins 'https://build.ros.org'
Connected to Jenkins version '2.263.3'
Updating job 'upload_main'
    <<<
    --- remote config
    +++ new config
    @@ -12,0 +13,3 @@
    +    <hudson.plugins.heavy__job.HeavyJobProperty plugin="heavy-job@1.1">
    +      <weight>1</weight>
    +    </hudson.plugins.heavy__job.HeavyJobProperty>
    @@ -23 +26 @@
    -      <upstreamProjects>Krel_sync-packages-to-main,Mrel_sync-packages-to-main,Nrel_sync-packages-to-main</upstreamProjects>
    +      <upstreamProjects>Krel_sync-packages-to-main,Mrel_sync-packages-to-main,Nrel_sync-packages-to-main,import_upstream</upstreamProjects>
    @@ -41 +44 @@
    -    <hudson.tasks.Mailer plugin="mailer@1.29">
    +    <hudson.tasks.Mailer plugin="mailer@1.32.1">
    >>>
Updating job 'upload_testing'
    <<<
    --- remote config
    +++ new config
    @@ -12,0 +13,3 @@
    +    <hudson.plugins.heavy__job.HeavyJobProperty plugin="heavy-job@1.1">
    +      <weight>1</weight>
    +    </hudson.plugins.heavy__job.HeavyJobProperty>
    @@ -23 +26 @@
    -      <upstreamProjects>Krel_sync-packages-to-testing_xenial_amd64,Krel_sync-packages-to-testing_xenial_arm64,Krel_sync-packages-to-testing_xenial_armhf,Krel_sync-packages-to-testing_xenial_i386,Mrel_sync-packages-to-testing_bionic_amd64,Mrel_sync-packages-to-testing_bionic_arm64,Mrel_sync-packages-to-testing_bionic_armhf,Mrel_sync-packages-to-testing_stretch_amd64,Mrel_sync-packages-to-testing_stretch_arm64,Nrel_sync-packages-to-testing_buster_amd64,Nrel_sync-packages-to-testing_buster_arm64,Nrel_sync-packages-to-testing_focal_amd64,Nrel_sync-packages-to-testing_focal_arm64,Nrel_sync-packages-to-testing_focal_armhf</upstreamProjects>
    +      <upstreamProjects>Krel_sync-packages-to-testing_xenial_amd64,Krel_sync-packages-to-testing_xenial_arm64,Krel_sync-packages-to-testing_xenial_armhf,Krel_sync-packages-to-testing_xenial_i386,Mrel_sync-packages-to-testing_bionic_amd64,Mrel_sync-packages-to-testing_bionic_arm64,Mrel_sync-packages-to-testing_bionic_armhf,Nrel_sync-packages-to-testing_buster_amd64,Nrel_sync-packages-to-testing_buster_arm64,Nrel_sync-packages-to-testing_focal_amd64,Nrel_sync-packages-to-testing_focal_arm64,Nrel_sync-packages-to-testing_focal_armhf,import_upstream</upstreamProjects>
    @@ -41 +44 @@
    -    <hudson.tasks.Mailer plugin="mailer@1.29">
    +    <hudson.tasks.Mailer plugin="mailer@1.32.1">
    >>>
```

I just remedied that.

**Comment by clalancette** [comment]
> I just remedied that and manually triggered the upload job so that bloom should be available in all testing and main repositories.

Thanks, appreciated.

**Comment by mikaelarguedas** [comment]
Awesome, thanks @nuclearsandwich
