### ISSUE TITLE
Eloquent instructions are incorrect

### ISSUE THREAD

**Issue by LanderU** [ros2/sros2#266]
## Bug report

**Required Info:**

- Operating System:
  - GNU/Linux
- Installation type:
  - binaries
- Version or commit hash:
  - eloquent
- DDS implementation:
  - NA
- Client library (if applicable):
  - NA

#### Steps to reproduce issue

```
docker run -it osrf/ros-eloquent-desktop
$ apt update && apt install subversion -y
$ mkdir ~/sros2
$ cd ~/sros2/
$ svn checkout https://github.com/ros2/sros2/trunk/sros2/test/policies
root@8ff9a792bff0:~/sros2# ros2 security create_permission demo_keys /talker policies/sample_policy.xml
policy file 'policies/sample_policy.xml' does not exist
root@8ff9a792bff0:~/sros2/policies# ls
add_two_ints.policy.xml  common  minimal_action.policy.xml  permissions  policy_to_permissions.py  sample.policy.xml  single_context.policy.xml  talker_listener.policy.xml
root@8ff9a792bff0:~/sros2# ros2 security create_permission demo_keys /talker policies/sample.policy.xml 
Element 'enclaves': This element is not expected. Expected is ( profiles )., line 4
```

#### Expected behavior

Be able to use policies version for eloquent.

#### Actual behavior

Looks like the version of the policies are not well pinned in the SROS2_Linux.md version.

#### Additional information

----

**Comment by clalancette** [comment]
Eloquent is [end of life](https://docs.ros.org/en/rolling/Releases.html), so we probably won't be doing any further updates for it.  My suggestion is that you try out [Galactic](https://docs.ros.org/en/galactic/) or [Foxy](https://docs.ros.org/en/foxy/) instead.

I think this should probably be closed, but I'll leave that to the SROS 2 maintainers to do.

**Comment by ruffsl** [comment]
You'll want to use the templates from before in introduction of enclaves, so before foxy and Apr 2020:
https://github.com/ros2/sros2/commits/master/sros2/test/policies

**Comment by LanderU** [comment]
@ruffsl @clalancette, thanks a lot for your responses!
