### ISSUE TITLE
Specify Domain ID Through Command Line Argument

### ISSUE THREAD

**Issue by danthony06** [ros2/sros2#267]
#### Feature description
Add the ability to specify the target domain through a command line argument, rather than environment variable. Currently, the domain ID for the configuration is set via reading an environment variable. This is clunky for automation and is harder to reproduce software between different developer's environments. Instead, it would be nice if this were set via a command line option to make it more explicit and easier to track.

#### Implementation considerations
It's currently set via an environment variable, but that is easy to forget about. A command line argument makes it explicit, but we can always use an environment variable as a fallback option.

**Comment by ruffsl** [comment]
I think adding support a user provided config file would offer a more comprehensive approach to customization of the security certificate generation. This could extend beyond Domains ID, but also to certificate expiration dates, middleware presets, key storage formats, etc. A config file approach used by other tools in the ros ecosystem, like rviz, ros1_bridge, colcon, would be familiar to many ROS users, and could be a bit more sustainable than adding ever more niche or middleware specific command line argument options.

This is sort of akin to what I tried before with keymint:

* https://github.com/keymint/keymint_tools/tree/04a14e8da96e6e0c5fc16198b6b232b91d095f41
* https://github.com/ruffsl/keymint_ws/tree/cc9306117b12a61989466c2e728304ccd54dc65c/profile/package.defaults
