### ISSUE TITLE
connext

### ISSUE THREAD

**Issue by NateBu** [ros2/sros2#279]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by clalancette** [comment]
Closing this out, as there is no information in here.

**Comment by NateBu** [comment]
Weird, I didn't deliberately submit this in the first place. Not sure how it got here
