### ISSUE TITLE
[Question] Security build option for rmw_fastrtps

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/sros2#294]
### Description

https://github.com/ros2/sros2/blob/master/SROS2_Linux.md tells that 

> Note: Fast-RTPS requires an additional CMake flag to build the security plugins so the colcon invocation needs to be modified to pass:
> colcon build --symlink-install --cmake-args -DSECURITY=ON

Is this really required to set? i confirmed that without rebuilding the discovery does not work, this mean security did work?

- It seems that `HAVE_SECURITY` is enabled to build security implementation in default for both Fast-DDS and rmw_fastrtps?
- What about the debian packages? if above description is true, we cannot use security features with rmw_fastrtps?

reference ticket: https://github.com/osrf/ros2_test_cases/issues/1306

**Comment by clalancette** [comment]
> > 
> 
> Is this really required to set? i confirmed that without rebuilding the discovery does not work, this mean security did work?

Yes, correct.

> * What about the debian packages? if above description is true, we cannot use security features with rmw_fastrtps?

No, in the debian packages we explicitly set `-DSECURITY=ON` while building so that security works.

If you are finding that this is *not* the case, then we may have lost a patch somewhere along the way.

**Comment by fujitatomoya** [comment]
Ah okay, only required source build. got it! i think Fast-DDS intentionally disables it because of some user does not need security... understood.

**Comment by mikaelarguedas** [comment]
It is not in the official ROS 2 documentation, but if the colcon default metadata are setup this is done automatically:
https://github.com/colcon/colcon-metadata-repository/blob/f0ea17f9a0e70ec0e0e15f869deec2b9f942607d/fastrtps.meta#L4

**Comment by fujitatomoya** [comment]
@mikaelarguedas thanks for the info!
