### ISSUE TITLE
[CI] mirroring to master fails

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/sros2#297]
There is an github action attempting to mirror rolling to master.

It has been introduced in https://github.com/ros2/sros2/commit/cfd25e7eaf3c8facc3b6b42e84e278b38e8b5eed and has been failing ever since.

<details>

```
Error: Failed to update ref: HttpError: Changes must be made through a pull request. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
```

</details>

@paudrow @clalancette Is there specific permissions to set so that this action can push to master ?

**Comment by clalancette** [comment]
> @paudrow @clalancette Is there specific permissions to set so that this action can push to master ?

No, it's just that `master` and `rolling` got out of sync at some point and we never resolved it.  At this point we should just remove that action, it doesn't serve any purpose anymore.

**Comment by mikaelarguedas** [comment]
Sounds good https://github.com/ros2/sros2/pull/298.

And the master branch is still there only for historical reasons but doesn't serve any purpose and doesnt need to be updated anymore is that right ?

**Comment by clalancette** [comment]
> And the master branch is still there only for historical reasons but doesn't serve any purpose and doesnt need to be updated anymore is that right ?

Yes, exactly.
