### ISSUE TITLE
What does distribute_key do?

### ISSUE THREAD

**Issue by sloretz** [ros2/sros2#60]
Calling `ros2 security distribute_key demo_keys output.fastrtps.keystore` on windows 10 results in no output on stdout. I'm not sure what it does. Guessing from the help text, I might expect that the result is a file named `output.fastrtps.keystore` which contains previously created keys, but I don't see any new files.

**Comment by mikaelarguedas** [comment]
https://github.com/ros2/sros2/blob/54394af2460b9a12f47c093b45cc53fddd7bbbaf/sros2/api/__init__.py#L549-L550

**Comment by sloretz** [comment]
Oops, thanks!
