### ISSUE TITLE
Rename generate_permissions to generate_policies?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/sros2#77]
When trying to use the `ros2 security generate_permissions` based only on the help message:
```
ros2 security generate_permissions -h
usage: ros2 security generate_permissions [-h] POLICY_FILE_PATH

Generate permissions

positional arguments:
  POLICY_FILE_PATH  path of the permission yaml file
```

I was surprised by the behavior.

What I understood the verb was doing: "Generate permissions based on a YAML policy file"

Actual behavior: "Look at the ROS graph and generate a YAML policy file but no permission files"

I suggest renaming the verb to reduce ambiguity and add a more complete help message than "Generate permissions".

@ross-desmond @ruffsl please let me know if this makes sense and/or if you have any suggestion on the approach (I opened #78 with the suggested change)

**Comment by ruffsl** [comment]
I think I might have addressed this in my unmerged PR https://github.com/ros2/sros2/pull/72 , specifically here when naming the verb to be used with rosgraph to populate a policy file. 

https://github.com/ros2/sros2/pull/72/files#diff-8825d563d227e6244a4d3ed88137d4e7R60

If you could review my PR to check it's verbs are consistent, then once it gets merged with the ready CI, then this would be resolved as well.

**Comment by mikaelarguedas** [comment]
Thanks @ruffsl, given the size of the PR I'm not sure I'll be able to review it all shortly but I'll try the code and skim through the names.

**Comment by mikaelarguedas** [comment]
The verb name looks good to me :+1: the help message from this PR could be used in #72 though as it currently just says "Generate permissions".

Closing this in favor or #72 and #80 then
