### ISSUE TITLE
Easy way to generate artifacts for all nodes in policy file

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/sros2#82]
## Feature request
Opening this ticket for feedback on the approach before starting implementation

#### Feature description

Provide a Python verb as well as CMake way of generating artifacts for all nodes listed in the policies file.

##### Context:
We can now have an automatically generated policies file for a ROS system (`generate_permissions`).
To generate artifacts for a set of nodes in the system we can use `ros2_secure_node`.
However this requires to explicitly list the nodes to create security artifacts for, which will result in a long handwritten macro call for a non-trivial (e.g. 50 nodes) system.

##### Problems it will solve:
- CMake changes: writing exhaustive list of nodes by hand for CMake macro call
- Python verb: A way to generate artifacts for all nodes without having to type many commands or create a CMake package

#### Implementation considerations

We could implement the feature in CMake and in Python.
In CMake: we could add an `ALL` option to the macro, in which case it would generate artifacts for the nodes listed under `NODES` and all the nodes present in the policy file.

In Python: we could provide a new verb e.g. `autogenerate_artifacts` that would require a policy file and optionnaly take a keystore path. It would create a keystore if needed and then generate keys and permissions for all the nodes listed in the policies file.

I'm planning on starting with the Python verb and then the CMake changes.

@ross-desmond @ruffsl any feedback on the approach will be very appreciated :)

**Comment by mikaelarguedas** [comment]
@mjcarroll do you have any feedback on the approach before starting the implementation?

**Comment by ruffsl** [comment]
How do we want to handle the case where permission files for a given identity pre-exists in the keystore?

**Comment by mikaelarguedas** [comment]
That's a good question, currently `sros2` and `sros2_cmake` overwrite existing permission files.
I was not planning on modifying the current behavior

**Comment by mjcarroll** [comment]
@mikaelarguedas This all sounds reasonable to me.  It would certainly save some time and improve maintainability in the case that you mentioned (50+ nodes?).

Out of curiosity, are you currently working with systems with that many secure nodes?

**Comment by ruffsl** [comment]
> Out of curiosity, are you currently working with systems with that many secure nodes?

Even using the humble turtle bot 3 with SROS2 involves many nodes, so automation would be welcome:

https://github.com/ruffsl/keymint_ws/blob/sros2_demo/profile/comarmor.d/turtlebot3.xml

**Comment by mikaelarguedas** [comment]
> Out of curiosity, are you currently working with systems with that many secure nodes?

Not at the moment, I was trying some Turtlebot3 examples, and just to run a simulated turtlebot3 with cartographer and teleop there are 19 nodes running making the explicit listing a bit cumbersome

**Comment by mikaelarguedas** [comment]
Python implementation done in #107 and CMake equivalent in #108
